### ISSUE TITLE
Query failing

### ISSUE THREAD

**Issue by dnishiyama** [evertheylen/notion-export-ics#5]
When I'm trying to export the calendar with the webapp.py I run into the following error. The ics that is exported doesn't have any content. Any idea what might be up? Looks like Notion updated their API last month.

Traceback (most recent call last):
  File ".../notion/notion-export-ics/webapp.py", line 38, in make_ics
    cal = get_ical(client, calendar_url, title_format)
  File ".../notion/notion-export-ics/notion_ics.py", line 27, in get_ical
    calendar_query = calendar_view.build_query()
  File ".../notion/collection.py", line 249, in build_query
    "query"
KeyError: 'query'

**Comment by elblogbruno** [comment]
https://github.com/jamalex/notion-py/pull/190 I made a pull request fixing the issue. A quick one is to manually modify the notion/collection.py go to the line 249 and change "query" for "query2".
